name: flama_bindings
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^9.0.0
  lints: ^2.1.0
  test: ^1.24.0
