name: flama_bindings
description: llama.cpp bindings for flama package.
version: 0.0.1+3
repository: https://github.com/luiscib3r/flama

environment:
  sdk: ^3.2.6

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^9.0.0
  lints: ^2.1.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
