name: flama_flutter_libs
description: 'llama.cpp libraries for flama_bindings packages'
version: 0.0.2+1
repository: https://github.com/luiscib3r/flama

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flama: ^0.0.2+1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
