name: flama
description: Flama is a Dart package designed to streamline interactions with\
  llama models through the llama.cpp API, facilitating seamless integration\
  and usage within Dart projects.
version: 0.0.1
repository: https://github.com/luiscib3r/flama

environment:
  sdk: ^3.2.6

dependencies:
  ffi: ^2.1.0
  flama_bindings:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
